baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "de-de"
title = "ML-Design"
theme = "ml-design"

[[menu.main]]
  name = "Home"
  weight = -110
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Kontakt"
  weight = -80
  identifier = "kontakt"
  url = "/kontakt"

[[menu.main]]
  name = "Impressum"
  weight = -70
  identifier = "impressum"
  url = "/impressum"